insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AF', 'Afghanistan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AX', '?land Islands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AL', 'Albania');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('DZ', 'Algeria');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AS', 'American Samoa');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AD', 'Andorra');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AO', 'Angola');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AI', 'Anguilla');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AQ', 'Antarctica');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AG', 'Antigua and Barbuda');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AR', 'Argentina');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AM', 'Armenia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AW', 'Aruba');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AU', 'Australia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AT', 'Austria');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AZ', 'Azerbaijan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BS', 'Bahamas');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BH', 'Bahrain');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BD', 'Bangladesh');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BB', 'Barbados');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BY', 'Belarus');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BE', 'Belgium');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BZ', 'Belize');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BJ', 'Benin');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BM', 'Bermuda');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BT', 'Bhutan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BO', 'Bolivia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BA', 'Bosnia and Herzegovina');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BW', 'Botswana');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BV', 'Bouvet Island');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BR', 'Brazil');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('IO', 'British Indian Ocean Territory');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BN', 'Brunei Darussalam');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BG', 'Bulgaria');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BF', 'Burkina Faso');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('BI', 'Burundi');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('KH', 'Cambodia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CM', 'Cameroon');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CA', 'Canada');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CV', 'Cape Verde');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('KY', 'Cayman Islands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CF', 'Central African Republic');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TD', 'Chad');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CL', 'Chile');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CN', 'China');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CX', 'Christmas Island');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CC', 'Cocos (Keeling) Islands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CO', 'Colombia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('KM', 'Comoros');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CG', 'Congo');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CD', 'Congo');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CK', 'Cook Islands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CR', 'Costa Rica');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CI', 'Cote Divoire');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('HR', 'Croatia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CU', 'Cuba');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CY', 'Cyprus');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CZ', 'Czech Republic');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('DK', 'Denmark');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('DJ', 'Djibouti');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('DM', 'Dominica');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('DO', 'Dominican Republic');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('EC', 'Ecuador');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('EG', 'Egypt');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SV', 'El Salvador');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GQ', 'Equatorial Guinea');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('ER', 'Eritrea');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('EE', 'Estonia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('ET', 'Ethiopia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('FK', 'Falkland Islands (Malvinas)');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('FO', 'Faroe Islands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('FJ', 'Fiji');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('FI', 'Finland');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('FR', 'France');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GF', 'French Guiana');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PF', 'French Polynesia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TF', 'French Southern Territories');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GA', 'Gabon');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GM', 'Gambia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GE', 'Georgia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('DE', 'Germany');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GH', 'Ghana');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GI', 'Gibraltar');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GR', 'Greece');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GL', 'Greenland');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GD', 'Grenada');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GP', 'Guadeloupe');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GU', 'Guam');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GT', 'Guatemala');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GG', 'Guernsey');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GN', 'Guinea');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GW', 'Guinea-bissau');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GY', 'Guyana');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('HT', 'Haiti');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('HM', 'Heard Island & Mcdonald Islands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('VA', 'Holy See (Vatican City State)');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('HN', 'Honduras');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('HK', 'Hong Kong');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('HU', 'Hungary');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('IS', 'Iceland');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('IN', 'India');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('ID', 'Indonesia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('IR', 'Iran');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('IQ', 'Iraq');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('IE', 'Ireland');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('IM', 'Isle of Man');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('IL', 'Israel');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('IT', 'Italy');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('JM', 'Jamaica');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('JP', 'Japan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('JE', 'Jersey');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('JO', 'Jordan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('KZ', 'Kazakhstan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('KE', 'Kenya');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('KI', 'Kiribati');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('KP', 'Korea');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('KR', 'Korea');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('KW', 'Kuwait');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('KG', 'Kyrgyzstan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('LA', 'Lao People Democratic Republic');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('LV', 'Latvia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('LB', 'Lebanon');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('LS', 'Lesotho');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('LR', 'Liberia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('LY', 'Libyan Arab Jamahiriya');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('LI', 'Liechtenstein');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('LT', 'Lithuania');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('LU', 'Luxembourg');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MO', 'Macao');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MK', 'Macedonia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MG', 'Madagascar');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MW', 'Malawi');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MY', 'Malaysia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MV', 'Maldives');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('ML', 'Mali');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MT', 'Malta');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MH', 'Marshall Islands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MQ', 'Martinique');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MR', 'Mauritania');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MU', 'Mauritius');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('YT', 'Mayotte');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MX', 'Mexico');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('FM', 'Micronesia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MD', 'Moldova');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MC', 'Monaco');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MN', 'Mongolia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('ME', 'Montenegro');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MS', 'Montserrat');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MA', 'Morocco');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MZ', 'Mozambique');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MM', 'Myanmar');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NA', 'Namibia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NR', 'Nauru');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NP', 'Nepal');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NL', 'Netherlands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AN', 'Netherlands Antilles');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NC', 'New Caledonia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NZ', 'New Zealand');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NI', 'Nicaragua');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NE', 'Niger');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NG', 'Nigeria');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NU', 'Niue');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NF', 'Norfolk Island');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('MP', 'Northern Mariana Islands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('NO', 'Norway');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('OM', 'Oman');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PK', 'Pakistan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PW', 'Palau');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PS', 'Palestinian Territory');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PA', 'Panama');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PG', 'Papua New Guinea');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PY', 'Paraguay');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PE', 'Peru');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PH', 'Philippines');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PN', 'Pitcairn');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PL', 'Poland');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PT', 'Portugal');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PR', 'Puerto Rico');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('QA', 'Qatar');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('RE', 'Reunion');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('RO', 'Romania');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('RU', 'Russian Federation');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('RW', 'Rwanda');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SH', 'Saint Helena');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('KN', 'Saint Kitts and Nevis');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('LC', 'Saint Lucia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('PM', 'Saint Pierre and Miquelon');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('VC', 'Saint Vincent and The Grenadines');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('WS', 'Samoa');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SM', 'San Marino');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('ST', 'Sao Tome and Principe');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SA', 'Saudi Arabia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SN', 'Senegal');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('RS', 'Serbia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SC', 'Seychelles');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SL', 'Sierra Leone');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SG', 'Singapore');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SK', 'Slovakia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SI', 'Slovenia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SB', 'Solomon Islands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SO', 'Somalia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('ZA', 'South Africa');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GS', 'South Georgia...');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('ES', 'Spain');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('LK', 'Sri Lanka');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SD', 'Sudan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SR', 'Suriname');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SJ', 'Svalbard and Jan Mayen');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SZ', 'Swaziland');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SE', 'Sweden');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('CH', 'Switzerland');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('SY', 'Syrian Arab Republic');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TW', 'Taiwan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TJ', 'Tajikistan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TZ', 'Tanzania');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TH', 'Thailand');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TL', 'Timor-leste');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TG', 'Togo');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TK', 'Tokelau');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TO', 'Tonga');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TT', 'Trinidad and Tobago');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TN', 'Tunisia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TR', 'Turkey');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TM', 'Turkmenistan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TC', 'Turks and Caicos Islands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('TV', 'Tuvalu');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('UG', 'Uganda');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('UA', 'Ukraine');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('AE', 'United Arab Emirates');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('GB', 'United Kingdom');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('US', 'United States');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('UM', 'United States Minor Outlying Islands');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('UY', 'Uruguay');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('UZ', 'Uzbekistan');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('VU', 'Vanuatu');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('VE', 'Venezuela');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('VN', 'Viet Nam');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('VG', 'Virgin Islands (British)');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('VI', 'Virgin Islands (US)');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('WF', 'Wallis and Futuna');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('EH', 'Western Sahara');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('YE', 'Yemen');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('ZM', 'Zambia');
insert into COUNTRIES (COUNTRY_ID, COUNTRY_NAME) values ('ZW', 'Zimbabwe');